version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shibo-postgres
    environment:
      POSTGRES_DB: shibo_tg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shibo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shibo-redis
    ports:
      - "6379:6379"
    networks:
      - shibo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shibo-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/shibo_tg
      REDIS_URL: redis://redis:6379
      PORT: 3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - shibo-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:

networks:
  shibo-network:
    driver: bridge