[build]
builder = "nixpacks"
buildCommand = "npm install && cd telegram-webapp && npm install && npm run build && cd .."

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[deploy.variables]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

[[services]]
name = "web"
port = 3000