[build]
  # Не выполнять никакие команды сборки
  command = ""
  # Публиковать файлы из текущей директории
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/r/:code"
  to = "/index.html?ref=:code"
  status = 200